### ISSUE TITLE
1.2.6如何使用源代码进行build和运行

### ISSUE THREAD

**Issue by simonway** [mushan0x0/AI0x0.com#125]
**描述错误**
下载了1.2.6的源代码后，如何使用npm进行build和运行。在build的时候，使用的命令为：
npm run-script build
 报如下错误：
> ai0x0.com@0.0.1 build /Users/simon/Downloads/AI0x0.com-1.2.6
> dumi build && cp CNAME dist

/Users/simon/.nvm/versions/node/v11.15.0/lib/node_modules/dumi/node_modules/@umijs/utils/compiled/@clack/prompts/index.js:1
(function(){var t={328:function(t,e,s){let r=s(224);let n=!("NO_COLOR"in process.env||process.argv.includes("--no-color"))&&("FORCE_COLOR"in process.env||process.argv.includes("--color")||process.platform==="win32"||r.isatty(1)&&process.env.TERM!=="dumb"||"CI"in process.env);let formatter=(t,e,s=t)=>r=>{let n=""+r;let a=n.indexOf(e,t.length);return~a?t+replaceClose(n,e,s,a)+e:t+n+e};let replaceClose=(t,e,s,r)=>{let n=t.substring(0,r)+s;let a=t.substring(r+e.length);let u=a.indexOf(e);return~u?n+replaceClose(a,e,s,u):n+a};let createColors=(t=n)=>({isColorSupported:t,reset:t?t=>`${t}`:String,bold:t?formatter("","",""):String,dim:t?formatter("","",""):String,italic:t?formatter("",""):String,underline:t?formatter("",""):String,inverse:t?formatter("",""):String,hidden:t?formatter("",""):String,strikethrough:t?fo

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/simon/.nvm/versions/node/v11.15.0/lib/node_modules/dumi/node_modules/@umijs/utils/dist/index.js:76:28)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ai0x0.com@0.0.1 build: `dumi build && cp CNAME dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ai0x0.com@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simon/.npm/_logs/2023-03-31T04_05_26_725Z-debug.log

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[MacOS Catalina]
 - 系统版本 [10.15.7]

**其他上下文**
不知道是不是build的命令有问题，还是有其他的方法build。希望提供build的命令和run 的命令

**Comment by mushan0x0** [comment]
这个是官网的源码哦，不是程序的
